/**** nueva version con grupo y datos adicionales */
SELECT G.*,
(SELECT NOMBRE FROM VALORES_CLAVES WHERE CLAVE = 'CADN' AND VALOR_CLAVE = G.CODIGO_CADENA) D_CODIGO_CADENA,
(SELECT NOMBRE FROM VALORES_CLAVES WHERE CLAVE = 'CANALV' AND VALOR_CLAVE = G.CODIGO_CANAL_VTA) D_CODIGO_CANAL_VTA
FROM
(
    SELECT E.*, F.ALMACEN_PEDIDO, F.IMPORTE_BRUTO, F.CLIENTE,
    (SELECT RAZON_SOCIAL2 FROM VA_CLIENTES WHERE CODIGO_EMPRESA = '004' AND CODIGO_RAPIDO = F.CLIENTE) D_CLIENTE,
    (SELECT VALOR_CLAVE FROM CLIENTES_CLAVES_ESTADISTICAS WHERE CODIGO_EMPRESA = '004' AND CODIGO_CLIENTE = F.CLIENTE AND CLAVE = 'CADN') CODIGO_CADENA,
    (SELECT VALOR_CLAVE FROM CLIENTES_CLAVES_ESTADISTICAS WHERE CODIGO_EMPRESA = '004' AND CODIGO_CLIENTE = F.CLIENTE AND CLAVE = 'CANALV') CODIGO_CANAL_VTA,
    (SELECT NOMBRE FROM ALMACENES WHERE CODIGO_EMPRESA = '004' AND ALMACEN = F.ALMACEN_PEDIDO) D_CODIGO_ALMACEN,
    (CASE E.CODIGO_SECUENCIA
    WHEN '020' THEN 1
    WHEN '032' THEN 2
    WHEN '033' THEN 2
    WHEN '034' THEN 2
    WHEN '030' THEN 4
    WHEN '031' THEN 4
    WHEN '040' THEN 4
    WHEN '050' THEN 4
    WHEN '060' THEN 4
    WHEN '065' THEN 3
    WHEN '070' THEN 5
    WHEN '130' THEN 5
    WHEN '140' THEN 5
    WHEN '075' THEN 6
    WHEN '120' THEN 7
    WHEN '080' THEN 8
    WHEN '150' THEN 9
    WHEN '160' THEN 9
    WHEN '160' THEN 10
    WHEN '190' THEN 11
    WHEN '999' THEN 12
    WHEN '100' THEN 13
    ELSE 0 END) ORDEN,
    (CASE E.CODIGO_SECUENCIA
    WHEN '020' THEN 'Confirmar pedido'
    WHEN '032' THEN 'Validacion Call Center'
    WHEN '033' THEN 'Validacion Call Center'
    WHEN '034' THEN 'Validacion Call Center'
    WHEN '030' THEN 'Validacion Financiera'
    WHEN '031' THEN 'Validacion Financiera'
    WHEN '040' THEN 'Validacion Financiera'
    WHEN '050' THEN 'Validacion Financiera'
    WHEN '060' THEN 'Validacion Financiera'
    WHEN '065' THEN 'Validacion Gestor'
    WHEN '070' THEN 'Emitir pedido'
    WHEN '130' THEN 'Validacion Solicitante'
    WHEN '140' THEN 'Validacion Solicitante'
    WHEN '075' THEN 'Gestionar Hoja de Carga'
    WHEN '120' THEN 'Alistar pedido'
    WHEN '080' THEN 'Realizar Facturacion'
    WHEN '150' THEN 'Despacho-Entregar Ped.'
    WHEN '160' THEN 'Despacho-Entregar Ped.'
    WHEN '160' THEN 'Pedido Entregado'
    WHEN '190' THEN 'Logistica Inversa'
    WHEN '999' THEN 'Pedido Descartado'
    WHEN '100' THEN 'Cerrar/anular pedido'
    ELSE '' END) GRUPO
    FROM
    (
    SELECT A.NUMERO_EXPEDIENTE,
    A.FECHA_INICIO,
    A.ITEMA041 SERIE,
    A.ITEMN002 NRO_PEDIDO,
    A.ITEMN001 PERIODO,
    B.CODIGO_SECUENCIA,
    A.TIPO_EXPEDIENTE,
    A.STATUS_EXPEDIENTE,
    B.STATUS_TAREA,
    C.DESCRIPCION
    FROM
    CRMEXPEDIENTES_CAB A,
    CRMEXPEDIENTES_LIN B,
    CRMSECUENCIA_TAREAS C,
    CRMESTADOS_TAREAS D,
    CRMTIPOS_TAREA E
    WHERE A.EMPRESA=B.EMPRESA
    AND A.NUMERO_EXPEDIENTE=B.NUMERO_EXPEDIENTE
    AND (B.EMPRESA=C.EMPRESA AND B.CODIGO_SECUENCIA = C.CODIGO_SECUENCIA)
    AND A.TIPO_EXPEDIENTE=C.TIPO_EXPEDIENTE
    AND B.STATUS_TAREA = D.ESTADO_TAREA
    AND B.EMPRESA = D.EMPRESA
    AND E.TIPO_TAREA = B.TIPO_TAREA
    AND E.EMPRESA=B.EMPRESA
    AND A.EMPRESA = '004'
    AND A.FECHA_INICIO BETWEEN TO_DATE('01/01/2022', 'DD/MM/YYYY') AND TO_DATE('02/08/2022', 'DD/MM/YYYY')
    AND A.TIPO_EXPEDIENTE = '04003'
    AND (
        (A.STATUS_EXPEDIENTE = '01' AND B.STATUS_TAREA = '01') OR (A.STATUS_EXPEDIENTE = '99' AND B.CODIGO_SECUENCIA IN ('160','999','100') AND B.STATUS_TAREA IN ('82B','999','99'))
        )
    ) E LEFT JOIN PEDIDOS_VENTAS F
    ON E.PERIODO = F.EJERCICIO
    AND E.SERIE = F.NUMERO_SERIE
    AND E.NRO_PEDIDO = F.NUMERO_PEDIDO and empresa ='004'
) G
ORDER BY 1


/*******/

SELECT DISTINCT 1 cont,
G.FECHA_INICIO,
G.SERIE,
G.CODIGO_SECUENCIA,
G.TIPO_EXPEDIENTE,
G.STATUS_EXPEDIENTE,
G.STATUS_TAREA,
G.USUARIO_ALTA,
G.DESCRIPCION,
G.EMPRESA,
G.ALMACEN_PEDIDO,
G.CLIENTE,
G.D_CLIENTE,
G.CODIGO_CADENA,
G.CODIGO_CANAL_VTA,
G.D_CODIGO_ALMACEN,
G.GRUPO,
G.NUMERO_EXPEDIENTE,
G.NRO_PEDIDO,
G.PERIODO,
SUM(G.IMPORTE_BRUTO) IMPORTE_BRUTO,
G.ORDEN,
(SELECT NOMBRE FROM VALORES_CLAVES WHERE CLAVE = 'CADN' AND VALOR_CLAVE = G.CODIGO_CADENA) D_CODIGO_CADENA,
(SELECT NOMBRE FROM VALORES_CLAVES WHERE CLAVE = 'CANALV' AND VALOR_CLAVE = G.CODIGO_CANAL_VTA) D_CODIGO_CANAL_VTA,
G.GRUPO3_FACTURADO
FROM
(
SELECT DISTINCT E.*, F.ALMACEN_PEDIDO, NVL(F1.IMPORTE_BRUTO,F.IMPORTE_BRUTO) IMPORTE_BRUTO, F.CLIENTE,
(SELECT RAZON_SOCIAL2 FROM VA_CLIENTES WHERE CODIGO_EMPRESA = '004' AND CODIGO_RAPIDO = F.CLIENTE) D_CLIENTE,
(SELECT VALOR_CLAVE FROM CLIENTES_CLAVES_ESTADISTICAS WHERE CODIGO_EMPRESA = '004' AND CODIGO_CLIENTE = F.CLIENTE AND CLAVE = 'CADN') CODIGO_CADENA,
(SELECT VALOR_CLAVE FROM CLIENTES_CLAVES_ESTADISTICAS WHERE CODIGO_EMPRESA = '004' AND CODIGO_CLIENTE = F.CLIENTE AND CLAVE = 'CANALV') CODIGO_CANAL_VTA,
(SELECT NOMBRE FROM ALMACENES WHERE CODIGO_EMPRESA = '004' AND ALMACEN = F.ALMACEN_PEDIDO) D_CODIGO_ALMACEN,
(CASE WHEN E.CODIGO_SECUENCIA = '020' THEN 1
WHEN E.CODIGO_SECUENCIA = '032' THEN 2
WHEN E.CODIGO_SECUENCIA = '033' THEN 2
WHEN E.CODIGO_SECUENCIA = '034' THEN 2
WHEN E.CODIGO_SECUENCIA = '030' THEN 4
WHEN E.CODIGO_SECUENCIA = '031' THEN 4
WHEN E.CODIGO_SECUENCIA = '040' THEN 4
WHEN E.CODIGO_SECUENCIA = '050' THEN 4
WHEN E.CODIGO_SECUENCIA = '060' THEN 4
WHEN E.CODIGO_SECUENCIA = '065' THEN 3
WHEN E.CODIGO_SECUENCIA = '070' THEN 5.1
WHEN E.CODIGO_SECUENCIA = '130' THEN 5
WHEN E.CODIGO_SECUENCIA = '140' THEN 5
WHEN E.CODIGO_SECUENCIA = '075' THEN 6
WHEN E.CODIGO_SECUENCIA = '120' THEN 7
WHEN E.CODIGO_SECUENCIA = '080' THEN 8
WHEN E.CODIGO_SECUENCIA = '150' THEN 9
WHEN E.CODIGO_SECUENCIA = '160' AND E.STATUS_EXPEDIENTE = '01' THEN 9
WHEN E.CODIGO_SECUENCIA = '160' AND E.STATUS_EXPEDIENTE = '99' THEN 10
WHEN E.CODIGO_SECUENCIA = '190' THEN 11
WHEN E.CODIGO_SECUENCIA = '999' THEN 12
WHEN E.CODIGO_SECUENCIA = '100' THEN 13
ELSE 0 END) ORDEN,
(CASE WHEN E.CODIGO_SECUENCIA = '020' THEN '01. Confirmar pedido'
WHEN E.CODIGO_SECUENCIA = '032' THEN '02. Validacion Call Center'
WHEN E.CODIGO_SECUENCIA = '033' THEN '02. Validacion Call Center'
WHEN E.CODIGO_SECUENCIA = '034' THEN '02. Validacion Call Center'
WHEN E.CODIGO_SECUENCIA = '030' THEN '04. Validacion Financiera'
WHEN E.CODIGO_SECUENCIA = '031' THEN '04. Validacion Financiera'
WHEN E.CODIGO_SECUENCIA = '040' THEN '04. Validacion Financiera'
WHEN E.CODIGO_SECUENCIA = '050' THEN '04. Validacion Financiera'
WHEN E.CODIGO_SECUENCIA = '060' THEN '04. Validacion Financiera'
WHEN E.CODIGO_SECUENCIA = '065' THEN '03. Validacion Gestor'
WHEN E.CODIGO_SECUENCIA = '070' THEN '05.1 Emitir pedido'
WHEN E.CODIGO_SECUENCIA = '130' THEN '05. Validacion Solicitante'
WHEN E.CODIGO_SECUENCIA = '140' THEN '05. Validacion Solicitante'
WHEN E.CODIGO_SECUENCIA = '075' THEN '06. Gestionar Hoja de Carga'
WHEN E.CODIGO_SECUENCIA = '120' THEN '07. Alistar pedido'
WHEN E.CODIGO_SECUENCIA = '080' THEN '08. Realizar Facturacion'
WHEN E.CODIGO_SECUENCIA = '150' THEN '09. Despacho-Entregar Ped.'
WHEN E.CODIGO_SECUENCIA = '160' AND E.STATUS_EXPEDIENTE = '01' THEN '09. Despacho-Entregar Ped.'
WHEN E.CODIGO_SECUENCIA = '160' AND E.STATUS_EXPEDIENTE = '99' THEN '10. Pedido Entregado'
WHEN E.CODIGO_SECUENCIA = '190' THEN '11. Logistica Inversa'
WHEN E.CODIGO_SECUENCIA = '999' THEN '12. Pedido Descartado'
WHEN E.CODIGO_SECUENCIA = '100' THEN '13. Cerrar/anular pedido'
ELSE '' END) GRUPO,
(CASE WHEN E.CODIGO_SECUENCIA IN ('020', '032', '033', '034', '030', '031', '040', '050', '060', '065', '070', '130', '140', '075', '120', '080') THEN 'PENDIENTE'
WHEN E.CODIGO_SECUENCIA IN ('150', '160') THEN 'EJECUTADO'
WHEN E.CODIGO_SECUENCIA IN ('190', '999', '100') THEN 'REPROCESO' 
ELSE '' END) GRUPO3_FACTURADO
FROM
(
SELECT A.NUMERO_EXPEDIENTE,
A.FECHA_INICIO,
A.ITEMA041 SERIE,
A.ITEMN002 NRO_PEDIDO,
A.ITEMN001 PERIODO,
B.CODIGO_SECUENCIA,
A.TIPO_EXPEDIENTE,
A.STATUS_EXPEDIENTE,
A.CODIGO_EMPRESA,
A.USUARIO_ALTA,
B.STATUS_TAREA,
C.DESCRIPCION,
A.EMPRESA
FROM
CRMEXPEDIENTES_CAB A,
CRMEXPEDIENTES_LIN B,
CRMSECUENCIA_TAREAS C,
CRMESTADOS_TAREAS D,
CRMTIPOS_TAREA E
WHERE A.EMPRESA=B.EMPRESA
AND A.NUMERO_EXPEDIENTE=B.NUMERO_EXPEDIENTE
AND (B.EMPRESA=C.EMPRESA AND B.CODIGO_SECUENCIA = C.CODIGO_SECUENCIA)
AND A.TIPO_EXPEDIENTE=C.TIPO_EXPEDIENTE
AND B.STATUS_TAREA = D.ESTADO_TAREA
AND B.EMPRESA = D.EMPRESA
AND E.TIPO_TAREA = B.TIPO_TAREA
AND E.EMPRESA=B.EMPRESA
AND A.EMPRESA = '004'
AND A.FECHA_INICIO BETWEEN :fini and :ffin  
AND A.TIPO_EXPEDIENTE = '04003' and A.USUARIO_ALTA IN (:p_USUARIO)
AND
((A.STATUS_EXPEDIENTE = '01' AND B.STATUS_TAREA = '01') OR (A.STATUS_EXPEDIENTE = '99' AND B.CODIGO_SECUENCIA IN ('999','100') AND B.STATUS_TAREA IN ('999','99')) OR (A.STATUS_EXPEDIENTE = '99' AND B.CODIGO_SECUENCIA = '160' AND B.STATUS_TAREA = '82B'))
) E LEFT JOIN PEDIDOS_VENTAS F
ON E.EMPRESA = F.EMPRESA
AND E.PERIODO = F.EJERCICIO
AND E.SERIE = F.NUMERO_SERIE
AND E.NRO_PEDIDO = F.NUMERO_PEDIDO and substr(e.codigo_empresa,2,12) = f.cliente
and e.numero_expediente = (SELECT xd.numero_expediente FROM crmexpedientes_documentos xd WHERE xd.EMPRESA = e.empresa AND xd.id_documento=(SELECT pv.ID_CRM FROM PEDIDOS_VENTAS pv where pv.empresa=e.empresa and  pv.EJERCICIO=e.periodo AND pv.NUMERO_PEDIDO =e.nro_pedido and pv.numero_serie=e.serie))
LEFT JOIN
(
SELECT DISTINCT Lin.EMPRESA, Lin.NUMERO_PEDIDO, Lin.NUMERO_SERIE_PEDIDO, Lin.EJERCICIO_PEDIDO, Cab.IMPORTE_BRUTO
FROM ALBARAN_VENTAS Cab, ALBARAN_VENTAS_LIN Lin
WHERE Cab.EMPRESA = Lin.EMPRESA
AND Cab.EJERCICIO = Lin.EJERCICIO
AND Cab.NUMERO_SERIE = Lin.NUMERO_SERIE
AND Cab.NUMERO_ALBARAN = Lin.NUMERO_ALBARAN
AND Cab.FECHA_PEDIDO BETWEEN :fini AND :ffin
AND Cab.EMPRESA = '004' AND Lin.NUMERO_SERIE_PEDIDO <> 'SIM'
GROUP BY Lin.EMPRESA, Lin.NUMERO_PEDIDO, Lin.NUMERO_SERIE_PEDIDO, Lin.EJERCICIO_PEDIDO, Cab.IMPORTE_BRUTO
) F1
ON E.EMPRESA = F1.EMPRESA
AND E.PERIODO = F1.EJERCICIO_PEDIDO
AND E.SERIE = F1.NUMERO_SERIE_PEDIDO
AND E.NRO_PEDIDO = F1.NUMERO_PEDIDO
and e.numero_expediente = (SELECT xd.numero_expediente FROM crmexpedientes_documentos xd WHERE xd.EMPRESA = e.empresa AND xd.id_documento=(SELECT pv.ID_CRM FROM PEDIDOS_VENTAS pv where pv.empresa=e.empresa and  pv.EJERCICIO=e.periodo AND pv.NUMERO_PEDIDO =e.nro_pedido and pv.numero_serie=e.serie))
) G
WHERE G.SERIE <> 'SIM' AND G.ALMACEN_PEDIDO <> ' '
GROUP BY G.FECHA_INICIO,
G.SERIE,
G.CODIGO_SECUENCIA,
G.TIPO_EXPEDIENTE,
G.STATUS_EXPEDIENTE,
G.STATUS_TAREA,
G.DESCRIPCION,
G.EMPRESA,
G.ALMACEN_PEDIDO,
G.CLIENTE,
G.D_CLIENTE,
G.CODIGO_CADENA,
G.CODIGO_CANAL_VTA,
G.D_CODIGO_ALMACEN,
G.GRUPO,
G.NUMERO_EXPEDIENTE,
G.NRO_PEDIDO,
G.PERIODO,
G.ORDEN,
G.GRUPO3_FACTURADO,
G.USUARIO_ALTA
ORDER BY 2